repos:
    # Black PEP8 formatter
-   repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
    -   id: black
    # Simple QOL default precommit hooks.
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: check-ast
    -   id: end-of-file-fixer
    -   id: name-tests-test
    -   id: trailing-whitespace

default_language_version:
    python: python3.9

#fast_fail: true
